version: '3.9'

services:
  postgres:
    image: postgres:17-alpine
    platform: linux/amd64
    restart: always
    environment:
      POSTGRES_USER: r1
      POSTGRES_PASSWORD: r1
      POSTGRES_DB: r1
      TZ: UTC
    ports:
      - '5432:5432'
    volumes:
      - postgres_data_arm64:/var/lib/postgresql/data
    networks:
      - my_network

volumes:
  postgres_data_arm64:

networks:
  my_network:
    driver: bridge
